version: '2'
services:
  jira-postgresql:
    image: postgres:9.5-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: jira
      POSTGRES_DB: jiradb
      POSTGRES_PASSWORD: epieleimaengeiSu3eivahpe
    ports:
    - "5432:5432"
    volumes:
    - /disk1/atlassian/jira/db/data:/var/lib/postgresql/data/pgdata
  jira:
    image: cptactionhank/atlassian-jira:latest
    mem_limit: 16000000000
    volumes:
    - /disk1/atlassian/jira/data:/var/atlassian/jira
    - /disk1/atlassian/jira-logs:/opt/atlassian/jira/logs
    - /disk1/atlassian/jira-conf:/opt/atlassian/jira/conf
    ports:
    - "8080:8080"
    - "8081:8081"
    environment:
      CATALINA_OPTS: -Xms4096m -Xmx12288m -Datlassian.plugins.enable.wait=300
  confluence-postgresql:
    image: postgres:9.5-alpine
    mem_limit: 1000000000
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: confluence
      POSTGRES_DB: confluencedb
      POSTGRES_PASSWORD: zu4ooK6tahsohmah8chuV1su
    ports:
    - "5433:5432"
    volumes:
    - /disk1/atlassian/confluence/db:/var/lib/postgresql/data/pgdata
  confluence:
    image: atlassian/confluence-server:latest
    mem_limit: 16000000000
    volumes:
    - /disk1/atlassian/confluence/confluence-bin:/opt/atlassian/confluence/bin
    - /disk1/atlassian/confluence-conf:/opt/atlassian/confluence/conf
    - /disk1/atlassian/confluence/data:/var/atlassian/application-data/confluence
    ports:
    - "8090:8090"
    - "8091:8091"
    environment:
      CATALINA_OPTS: -Xms8000m -Xmx12288m -Datlassian.plugins.enable.wait=600 ${CATALINA_OPTS}
  nginx:
   image: nginx:stable
   volumes:
   - /disk1/nginx/conf.d:/etc/nginx/conf.d
   - /disk1/nginx/certs:/etc/nginx/certs
   ports:
   - "80:80"
   - "443:443":